<?php

declare(strict_types=1);

/** @var \Okaruto\Space\Renderer\TemplateInterface $this */

$languages = $this->languageSelect();

?>
<?php if (!empty($languages)) : ?>
<input id="languages" type="checkbox" class="toggleinput">
<div class="languages">
    <?php $currentLanguage = array_shift($languages); ?>
    <label for="languages">
        <span class="languages__flag" style="background-image: url('<?= $currentLanguage['image']; ?>');"></span>
    </label>
    <div class="languages__selector">
    <?php foreach ($languages as $language) : ?>
        <a href="<?= $language['url']; ?>"><span class="languages__flag" style="background-image: url('<?= $language['image']; ?>');"></span></a>
    <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>
